name: manual build

on: 
  workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Ninja
        run: choco install ninja

      - name: Configure CMake with Ninja
        run: cmake -S . -B build -G "Ninja"

      - name: Build
        run: cmake --build build

      - name: Run program
        run: build\app.exe

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp
          path: build/app.exe
